version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: reservas_db
    environment:
      POSTGRES_DB: reservas_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: reservas_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/reservas_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/target
      - ./uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: reservas_frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

volumes:
  postgres_data:
