@startuml
actor "SistemaAutomático" as Sys
participant "Reserva" as Res
participant "ColaDeEspera" as Cola
participant "Notificador" as Notif

Sys -> Res : verificarTiempo(ahora)
alt ahora >= horaInicio + 31min
    Sys -> Res : setEstado("Cancelada por No-Show")
    Sys -> Cola : obtenerSiguiente()
    alt hayPreReserva == true
        Cola -> "ReservaEnEspera" as R2 : setEstado("Confirmada")
        Sys -> Notif : notificarNuevoCliente(R2)
    else colaVacia
        Sys -> "Habitacion" : setEstado("Disponible")
    end
end
@enduml
